/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    // Primary button tokens
    'bg-components-button-primary-blue-bg-default',
    'bg-components-button-primary-blue-bg-hover',
    'bg-components-button-primary-blue-bg-active',
    'bg-components-button-primary-bg-disabled',
    'text-components-button-primary-text-default',
    'text-components-button-primary-text-hover',
    'text-components-button-primary-text-active',
    'text-components-button-primary-text-focus',
    'text-components-button-primary-text-disabled',
    'bg-components-button-primary-icon-default',
    'bg-components-button-primary-icon-hover',
    'bg-components-button-primary-icon-active',
    'bg-components-button-primary-icon-focus',
    'bg-components-button-primary-icon-disabled',
    // Secondary button tokens
    'bg-components-button-secondary-bg-default',
    'bg-components-button-secondary-bg-hover',
    'bg-components-button-secondary-bg-active',
    'bg-components-button-secondary-bg-focus',
    'bg-components-button-secondary-bg-disabled',
    'text-components-button-secondary-text-default',
    'text-components-button-secondary-text-hover',
    'text-components-button-secondary-text-active',
    'text-components-button-secondary-text-focus',
    'text-components-button-secondary-text-disabled',
    'bg-components-button-secondary-icon-default',
    'bg-components-button-secondary-icon-hover',
    'bg-components-button-secondary-icon-active',
    'bg-components-button-secondary-icon-focus',
    'bg-components-button-secondary-icon-disabled',
    'outline-components-button-secondary-border-default',
    'outline-components-button-secondary-border-hover',
    'outline-components-button-secondary-border-active',
    'outline-components-button-secondary-border-focus',
    'outline-components-button-secondary-border-disabled',
    // Secondary ghost tokens
    'bg-components-button-secondary-ghost-bg-hover',
    'bg-components-button-secondary-ghost-bg-active',
    'text-components-button-secondary-ghost-text-default',
    'text-components-button-secondary-ghost-text-hover',
    'text-components-button-secondary-ghost-text-active',
    'text-components-button-secondary-ghost-text-focus',
    'text-components-button-secondary-ghost-text-disabled',
    'bg-components-button-secondary-ghost-icon-default',
    'bg-components-button-secondary-ghost-icon-hover',
    'bg-components-button-secondary-ghost-icon-active',
    'bg-components-button-secondary-ghost-icon-focus',
    'bg-components-button-secondary-ghost-icon-disabled',
    // Tertiary button tokens
    'bg-components-button-tertiary-bg-default',
    'bg-components-button-tertiary-bg-hover',
    'bg-components-button-tertiary-bg-active',
    'bg-components-button-tertiary-bg-focus',
    'bg-components-button-tertiary-bg-disabled',
    'text-components-button-tertiary-text-default',
    'text-components-button-tertiary-text-hover',
    'text-components-button-tertiary-text-active',
    'text-components-button-tertiary-text-focus',
    'text-components-button-tertiary-text-disabled',
    'bg-components-button-tertiary-icon-default',
    'bg-components-button-tertiary-icon-hover',
    'bg-components-button-tertiary-icon-active',
    'bg-components-button-tertiary-icon-focus',
    'bg-components-button-tertiary-icon-disabled',
    'outline-components-button-tertiary-border-default',
    'outline-components-button-tertiary-border-hover',
    'outline-components-button-tertiary-border-active',
    'outline-components-button-tertiary-border-focus',
    'outline-components-button-tertiary-border-disabled',
    // Tertiary ghost tokens
    'bg-components-button-tertiary-ghost-bg-hover',
    'bg-components-button-tertiary-ghost-bg-active',
    'text-components-button-tertiary-ghost-text-default',
    'text-components-button-tertiary-ghost-text-hover',
    'text-components-button-tertiary-ghost-text-active',
    'text-components-button-tertiary-ghost-text-focus',
    'text-components-button-tertiary-ghost-text-disabled',
    'bg-components-button-tertiary-ghost-icon-default',
    'bg-components-button-tertiary-ghost-icon-hover',
    'bg-components-button-tertiary-ghost-icon-active',
    'bg-components-button-tertiary-ghost-icon-focus',
    'bg-components-button-tertiary-ghost-icon-disabled',
    // Neutral button tokens
    'bg-components-button-neutral-bg-default',
    'bg-components-button-neutral-bg-hover',
    'bg-components-button-neutral-bg-active',
    'bg-components-button-neutral-bg-focus',
    'bg-components-button-neutral-bg-disabled',
    'text-components-button-neutral-text-default',
    'text-components-button-neutral-text-hover',
    'text-components-button-neutral-text-active',
    'text-components-button-neutral-text-focus',
    'text-components-button-neutral-text-disabled',
    'bg-components-button-neutral-icon-default',
    'bg-components-button-neutral-icon-hover',
    'bg-components-button-neutral-icon-active',
    'bg-components-button-neutral-icon-focus',
    'bg-components-button-neutral-icon-disabled',
    // Focus border
    'border-border-focus',
    'outline-border-focus',
    // Primary color classes
    'bg-primary-500',
    'bg-primary-600',
    'bg-primary-700',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0efff',
          100: '#e8e6ff',
          200: '#d5d2ff',
          300: '#b8b3ff',
          400: '#9489ff',
          500: '#4D3EE0',
          600: '#3D31B3',
          700: '#2E2473',
          800: '#4D3EE0',
          900: '#4D3EE0',
          950: '#4D3EE0',
        },
      },
    },
  },
  plugins: [],
};
